# Generated by Django 5.2 on 2025-04-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='profession',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('self-employed', 'Self-employed'), ('other', 'Other')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('clinic', 'Clinic')], default='donor', max_length=20),
        ),
        migrations.AddField(
            model_name='recipient',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('clinic', 'Clinic')], default='recipient', max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='donor',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
