# Generated by Django 5.2 on 2025-04-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0002_donor_gender_donor_profession_donor_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Self-employed', 'Self-employed'), ('Other', 'Other')], default='None', max_length=20),
        ),
    ]
