# Generated by Django 5.2 on 2025-04-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0003_alter_donor_gender_alter_donor_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='requested_date',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='blood_group',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='hospital_report',
            field=models.FileField(null=True, upload_to='hospital_reports/'),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='requested_scheduleddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
