# Generated by Django 5.2 on 2025-04-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0004_remove_donationrequest_requested_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodstock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='bloodstock',
            name='units_available',
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='date_collected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
    ]
