# Generated by Django 5.2 on 2025-04-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0005_remove_bloodstock_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campschedule',
            name='location',
        ),
        migrations.AddField(
            model_name='campschedule',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campschedule',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campschedule',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
