# Generated by Django 5.2 on 2025-04-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0006_remove_campschedule_location_campschedule_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientrequest',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='requisition_form',
            field=models.FileField(blank=True, null=True, upload_to='requisition_forms/'),
        ),
    ]
