# Generated by Django 5.2 on 2025-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0007_recipientrequest_admin_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalclinic',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('clinic', 'Clinic')], default='hospital', max_length=20),
        ),
    ]
