# Generated by Django 5.2 on 2025-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0008_hospitalclinic_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='organization_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
