# Generated by Django 5.2 on 2026-05-10 10:17

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationapp', '0009_hospitalbloodrequest_organization_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminotp',
            options={'verbose_name': 'Admin OTP', 'verbose_name_plural': 'Admin OTPs'},
        ),
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name_plural': 'Admin Profiles'},
        ),
        migrations.AlterModelOptions(
            name='bloodstock',
            options={'verbose_name_plural': 'Blood Stock'},
        ),
        migrations.AlterModelOptions(
            name='campschedule',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Camp Schedules'},
        ),
        migrations.AlterModelOptions(
            name='donationrequest',
            options={'verbose_name_plural': 'Donation Requests'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name_plural': 'Donors'},
        ),
        migrations.AlterModelOptions(
            name='hospitalbloodrequest',
            options={'verbose_name_plural': 'Hospital Blood Requests'},
        ),
        migrations.AlterModelOptions(
            name='hospitalclinic',
            options={'verbose_name_plural': 'Hospitals/Clinics'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name_plural': 'Recipients'},
        ),
        migrations.AlterModelOptions(
            name='recipientrequest',
            options={'verbose_name_plural': 'Recipient Requests'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name_plural': 'User Roles'},
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalbloodrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hospitalclinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalclinic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='mobile_number',
            field=models.CharField(help_text='Contact mobile number for OTP verification', max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10-15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='date_collected',
            field=models.DateField(default=datetime.date(2026, 5, 10)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodstock',
            name='units',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='campschedule',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campschedule',
            name='district',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campschedule',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='donationapp.donor'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='hospital_report',
            field=models.FileField(blank=True, null=True, upload_to='hospital_reports/'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(45, message='Minimum weight required: 45 kg')]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='aadhaar',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Donor must be at least 18 years old'), django.core.validators.MaxValueValidator(65, message='Donor must be below 65 years old')]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10-15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='donor',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pin code must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Employee', 'Salaried Employee'), ('Self-employed', 'Self-employed'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('clinic', 'Clinic/Hospital')], default='donor', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='donationapp.hospitalclinic'),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalbloodrequest',
            name='units_required',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimum 1 unit required')]),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10-15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pin code must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('clinic', 'Clinic/Hospital')], default='clinic', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalclinic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='mobile_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10-15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10-15 digits.', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pin code must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('clinic', 'Clinic/Hospital')], default='recipient', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipientrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='recipientrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='donationapp.recipient'),
        ),
        migrations.AlterField(
            model_name='recipientrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipientrequest',
            name='units_required',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimum 1 unit required')]),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('donor', 'Donor'), ('recipient', 'Recipient'), ('clinic', 'Clinic/Hospital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donation_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bloodstock',
            unique_together={('blood_group', 'date_collected')},
        ),
        migrations.AddIndex(
            model_name='adminotp',
            index=models.Index(fields=['email'], name='donationapp_email_130fac_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstock',
            index=models.Index(fields=['blood_group'], name='donationapp_blood_g_6382b3_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodstock',
            index=models.Index(fields=['date_collected'], name='donationapp_date_co_dde2db_idx'),
        ),
        migrations.AddIndex(
            model_name='campschedule',
            index=models.Index(fields=['date'], name='donationapp_date_3ab65b_idx'),
        ),
        migrations.AddIndex(
            model_name='campschedule',
            index=models.Index(fields=['state', 'district'], name='donationapp_state_b74fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['status'], name='donationapp_status_a98b52_idx'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['donor', 'status'], name='donationapp_donor_i_8ae46c_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group'], name='donationapp_blood_g_265bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['state', 'district'], name='donationapp_state_276cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['aadhaar'], name='donationapp_aadhaar_d9bb3e_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbloodrequest',
            index=models.Index(fields=['status'], name='donationapp_status_a0bc57_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalbloodrequest',
            index=models.Index(fields=['blood_group'], name='donationapp_blood_g_4a0287_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalclinic',
            index=models.Index(fields=['organization_name'], name='donationapp_organiz_1c2982_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalclinic',
            index=models.Index(fields=['state', 'district'], name='donationapp_state_80d139_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['mobile_number'], name='donationapp_mobile__728438_idx'),
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['state', 'district'], name='donationapp_state_f59f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientrequest',
            index=models.Index(fields=['status'], name='donationapp_status_2e5d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientrequest',
            index=models.Index(fields=['blood_group'], name='donationapp_blood_g_2ebb15_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='donationapp_role_f682d3_idx'),
        ),
    ]
