from django.urls import path
from . import views

urlpatterns = [
     path('home', views.home, name='home'),
     path('mission', views.mission, name='mission'),
     path('vission', views.vission, name='vission'),
     path('team', views.team, name='team'),
     path('gallery', views.gallery, name='gallery'),
     path('donorlogin', views.donorlogin, name='donorlogin'),
     path('donorsignin', views.donorsignin, name='donorsignin'),
     path('donationrequest', views.donationrequest, name='donationrequest'),
     path('recipientlogin', views.recipientlogin, name='recipientlogin'),
     path('recipientsignin', views.recipientsignin, name='recipientsignin'),
     path('recipientrequest', views.recipientrequest, name='recipientrequest'),
     path('hospital/register/', views.hospital_register, name='hospital_register'),
     path('hospital/login/', views.hospital_login, name='hospital_login'),
     path('hospital/otp/', views.hospital_otp, name='hospital_otp'),
     path('hospital/request/', views.hospital_request_blood, name='hospital_request_blood'),
     path('adminlogin', views.adminlogin, name='adminlogin'),
     path('adminregister', views.adminregister, name='adminregister'),
     path('admin/list/', views.admin_list, name='adminlist'),
     path('admin/edit/<int:admin_id>/', views.admin_edit, name='admin_edit'),
     path('admin/delete/<int:admin_id>/', views.admin_delete, name='admin_delete'),
     path('admin/reset_password/<int:admin_id>/', views.admin_reset_password, name='admin_reset_password'),
     path('otp', views.otp, name='otp'),
     path('admin-otp/', views.admin_otp_verify, name='admin_otp_verify'),
     path('donordashboard', views.donordashboard, name='donordashboard'),
     path('dashboard', views.dashboard, name='dashboard'),
     path('hospitaldashboard', views.hospitaldashboard, name='hospitaldashboard'),
     path('recipientdashboard', views.recipientdashboard, name='recipientdashboard'),
     path('logout/', views.logout_view, name='logout'),
     path('add-stock/', views.add_stock, name='add_stock'),
     path('manage-stock/', views.manage_stock, name='manage_stock'),
     path('delete-stock/<int:pk>/', views.delete_expired_stock, name='delete_expired_stock'),
     path('manage-donors/', views.manage_donors, name='manage_donors'),
     path('manage-recipients/', views.manage_recipients, name='manage_recipients'),
     path('manage-hospitals/', views.manage_hospitals, name='manage_hospitals'),
     path('donor-request/<int:pk>/<str:action>/', views.update_donor_request, name='update_donor_request'),
     path('recipient-request/<int:pk>/<str:action>/', views.update_recipient_request, name='update_recipient_request'),
     path('hospital-request/<int:pk>/<str:action>/', views.update_hospital_request, name='update_hospital_request'),
     path('donor-request-reject-message/<int:pk>/', views.donor_rejection_message, name='donor_rejection_message'),
     path('blood-stock/', views.blood_stock_page, name='blood_stock_page'),
     path('manage-camps/', views.manage_camps, name='manage_camps'),
     path('add-camp/', views.add_camp, name='add_camp'),
     path('camp-schedule/', views.camp_schedule_page, name='camp_schedule_page'),

]